# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
prometheus:
  prometheusSpec:
    # Setting an empty object tells Prometheus to select monitors from all namespaces
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorNamespaceSelector: {}
    probeNamespaceSelector: {}
